name = "TransitionIndicators"
uuid = "5f5b98ec-1183-43e0-887a-12fdc55c52f7"
authors = ["Jan Swierczek-Jereczek <jan.jereczek@gmail.com>", "George Datseris <datseris.george@gmail.com>"]
version = "0.1.0"

[deps]
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
TimeseriesSurrogates = "c804724b-8c18-5caa-8579-6025a0767c70"
